### PR TITLE
Reduce sum

### PR DESCRIPTION
**Pull request by bbbales2**
I made some more changes to the tutorial. It's targeting cmdstanr now. I'd like to wait until we have the release candidate to finish it up (render as html, etc).

@wds15, I got lazy when merging this and deleted two sections you wrote.

```
The first three arguments of the reducer function must always be
present. These encode the start and end index of the partial sum as
well as a slice of the entire data over which the reduction is to
be performed. Any additional arguments are optional. These optional
arguments are shared (read-only) among all computations.
```

```
In case you turn this into a multi-level model where you introduce
groups of data for which you fit group specific parameters, then it is
often helpful to perform the slicing over the groups and use as
slicing argument of `reduce_sum` the group parameters themselves. This
leads to a more efficient parallelization, since the sliced argument
only gets doubled in memory while the shared arguments will be copied
as many times as there are splits of the large sum.
```

Mostly I deleted them cause I was feeling tired and too lazy to incorporate them back into the new text. I'm leaving them here for now.

Re: the first, in this latest version of the tutorial I defer even explaining the interface very much (I just link back to the manual). Keeps it shorter and more focused on just getting people up and running.

Re: the second, again, I was just keeping it simple and so left it out. This could go in an expanded section or something.

Both could definitely go back in, it would just take a little work.

### CODE REVIEW

**Comment by wds15** [comment]
Du u need any action from me?

**Comment by bbbales2** [comment]
Just letting you know it's safe to edit if yah want.

**Comment by wds15** [comment]
Thanks...I am fine...we should blog about this new beast.

**Comment by wds15** [comment]
looks like we need to update this as well, right?

**Comment by bbbales2** [comment]
Good catch. Now that Stanc3 is in I'll change this, run the cmdstanr benchmarks, and render it. Then we can do final review and blog it or whatever.

**Comment by wds15** [comment]
Btw...one learning from the vivid model is that it’s best to stuff as much as you can into the partial reduce function. This cuts down the ad tape a lot.

**Comment by bbbales2** [comment]
Whoops I've been working on this pull in the wrong repo. My bad.

**Pull request closed without merging**
